//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.14 at 12:51:51 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.omg.org/spec/DD/20100524/DI", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.net.woodstock.epm.bpmn2.beans;
