SELECT VI.PROC_INST_ID_,
       VI.TASK_ID_,
       VI.NAME_,
       VI.VAR_TYPE_,
	   VI.REV_,
       VI.DOUBLE_,
       VI.LONG_,
       VI.TEXT_,
       BA.BYTES_
  FROM ACT_HI_VARINST AS VI
       LEFT OUTER JOIN ACT_GE_BYTEARRAY AS BA ON (VI.BYTEARRAY_ID_ = BA.ID_)
 WHERE PROC_INST_ID_ = 1501
 ORDER BY NAME_